--Un comercio guarda la información de sus ventas en una tabla llamada `facturas`. 
-- 1-Elimine la tabla si existe. 
    DROP TABLE IF EXISTS FACTURAS;

-- 2-Cree la tabla con la siguiente estructura: 
    CREATE TABLE FACTURAS(
        NUMERO INT(10) UNSIGNED NOT NULL,
        NUMEROITEM SMALLINT UNSIGNED NOT NULL,
        DESCRIPCION VARCHAR(30),
        PRECIOPORTUNIDAD DECIMAL(5.2) UNSIGNED,
        CANTIDAD TINYINT UNSIGNED
    );
    
    ALTER TABLE FACTURAS ADD CONSTRAINT PK_FACTURAS PRIMARY KEY (NUMERO, NUMEROITEM);

-- 3-Ingrese algunos registros: 
    INSERT INTO FACTURAS (NUMERO, NUMEROITEM, DESCRIPCION, PRECIOPORTUNIDAD, CANTIDAD) VALUES (0000000100,1,'escuadra 20 cm.',2.50,20);
    INSERT INTO FACTURAS (NUMERO, NUMEROITEM, DESCRIPCION, PRECIOPORTUNIDAD, CANTIDAD) VALUES (0000000100,2,'escuadra 50 cm.',5.00,30);
    INSERT INTO FACTURAS (NUMERO, NUMEROITEM, DESCRIPCION, PRECIOPORTUNIDAD, CANTIDAD) VALUES (0000000100,3,'goma lapiz-tinta',0.35,100);
    INSERT INTO FACTURAS (NUMERO, NUMEROITEM, DESCRIPCION, PRECIOPORTUNIDAD, CANTIDAD) VALUES (0000000100,3,'goma lapiz-tinta',0.35,100);
    INSERT INTO FACTURAS (NUMERO, NUMEROITEM, DESCRIPCION, PRECIOPORTUNIDAD, CANTIDAD) VALUES (0000000102,1,'lapices coloresx6',4.40,50);
    INSERT INTO FACTURAS (NUMERO, NUMEROITEM, DESCRIPCION, PRECIOPORTUNIDAD, CANTIDAD) VALUES (0000000102,2,'lapices coloresx12',8.00,60);
    INSERT INTO FACTURAS (NUMERO, NUMEROITEM, DESCRIPCION, PRECIOPORTUNIDAD, CANTIDAD) VALUES (0000000255,1,'lapices coloresx24',12.35,100);
    INSERT INTO FACTURAS (NUMERO, NUMEROITEM, DESCRIPCION, PRECIOPORTUNIDAD, CANTIDAD) VALUES (0000000567,1,'compas plastico',12.00,50);
    INSERT INTO FACTURAS (NUMERO, NUMEROITEM, DESCRIPCION, PRECIOPORTUNIDAD, CANTIDAD) VALUES (0000000567,2,'compas metal',18.90,80);

 --4-Elimine la tabla `montofacturas` si existe.
    DROP TABLE IF EXISTS MONTOFACTURAS;

 --5-Se quiere guardar en una tabla denominada `montofacturas` el número de factura y el monto total en dinero de todos los items de cada factura (precioporunidad x cantidad). Cree la tabla con la siguiente estructura:
    CREATE TABLE MONTOFACTURAS (
    SELECT NUMERO, SUM (PRECIOPORTUNIDAD*CANTIDAD) AS TOTAL FROM
    FACTURAS GROUP BY NUMERO);
    
    ALTER TABLE MONTOFACTURAS ADD CONSTRAINT PK_MONTOFACTURAS PRIMARY KEY (NUMERO);
    
 --6-Realice una consulta de la tabla `facturas`, agrupando por `numero`, en la cual aparezca el número de factura y el monto total de todos sus items.
    SELECT NUMERO, SUM(PRECIOPORTUNIDAD*CANTIDAD) AS TOTAL FROM FACTURAS GROUP BY NUMERO;

 --7-Ingrese el resultado de la consulta anterior en la tabla `montofacturas`:
    INSERT INTO MONTOFACTURAS (NUMERO,TOTAL) SELECT NUMERO, SUM(PRECIOPORTUNIDAD*CANTIDAD) AS TOTAL FROM FACTURAS GROUP BY NUMERO;

 --8-Muestre todos los registros de la tabla `montofacturas`. 
    SHOW TABLE MONTOFACTURAS;
